engines:
    phpmd:
        enabled: true
    phpcodesniffer:
        enabled: true
    markdownlint:
        enabled: true
    shellcheck:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - javascript
                - php
    fixme:
        enabled: true
exclude_paths:
    - "vendor/*"
    - "config/*"
    - "bootstrap/*"
    - "database/*"
    - "storage/*"
    - "resources/assets/css/skin-*.css"
    - "resources/assets/js/AdminLTE.js"
    - "resources/assets/css/AdminLTE.css"
    - "resources/lang/en/*.php"
    - "*.blade.php"
    - "*.js"
