sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=sqlite TEST_SUITE=unit
  - DB=sqlite TEST_SUITE=integration

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/bower_components
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DB=mysql
      services:
        - mysql
    - php: 7.0
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install --quiet

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp/
  - make ci
  - gulp
  - make permissions

script:
  - make lint
  - make migrate
  - make seed
  - make rollback
  - make phpcs
  # - make phpmd
  - if [[ "$TEST_SUITE" = "unit" ]]; then make phpunit-ci; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then bash <(curl -s https://codecov.io/bash) -cF $TEST_SUITE; fi
  - if [[ "$TEST_SUITE" = "integration" ]]; then make integration-ci; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then bash <(curl -s https://codecov.io/bash) -cF $TEST_SUITE; fi
  - make phpdoc-check
  - make phpcpd
  - make lines

  # Clear the compiled file and then try to install without the dev dependencies to ensure everything still works
  - travis_retry composer install --no-dev --no-interaction --prefer-dist --no-suggest --quiet
  - php artisan optimize
  - php artisan app:version

after_script:
  - rm -rf $TRAVIS_BUILD_DIR/tmp/
  - find $TRAVIS_BUILD_DIR/storage/logs/*.log -type f -print -exec cat {} \;
  - cat $TRAVIS_BUILD_DIR/.env

notifications:
  email: false
