language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f
  
install:
  - composer install --no-interaction --prefer-source
  - npm install
  - bower install

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
  
# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
