sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=sqlite

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/bower_components
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=mysql
      services:
        - mysql
    - php: 7.0
      env: DB=mysql
      services:
        - mysql
    - php: 7.1
      env: DB=mysql
      services:
        - mysql
    - php: 5.6
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 5.6
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql
    - php: 7.1
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry yarn install --no-progress

before_script:
  - make ci
  - gulp
  # - php artisan js-localization:refresh
  - make permissions

script:
  - make lint
  - make migrate
  - make seed
  - make rollback
  - make phpcs
  # - make phpmd
  - make phpunit-ci
  - make phpdoc-check
  - make lines

  # Clear the compiled file and then try to install without the dev dependencies to ensure everything still works
  - travis_retry composer install --no-dev --no-interaction --prefer-dist --no-suggest --quiet
  - php artisan optimize
  - php artisan app:version

after_script:
  - find $TRAVIS_BUILD_DIR/storage/logs/*.log -type f -print -exec cat {} \;
  - cat $TRAVIS_BUILD_DIR/.env

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
