language: php

php:
    - 5.5.9
    - 5.5
    - 5.6
    - hhvm

sudo: false

install: travis_retry composer install --no-interaction --ignore-platform-reqs --no-scripts --prefer-source

script:
    - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
    - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover storage/coverage/clover.xml; fi;'

after_script:
    - bash -c 'vendor/bin/test-reporter --coverage-report=storage/coverage/clover.xml;'
