language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - travis_retry bower install -f
  
install:
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry npm install
  - travis_retry bower install

before_script:
  - chmod -R 777 storage
  - touch storage/database.sqlite

script:
  - php artisan migrate:refresh --no-interaction -vvv --seed

after_script:
  - ls -laR storage
  - cat storage/logs/*
  
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
  
# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
